### ISSUE TITLE
How do you install version 2.0.2?

### ISSUE THREAD

**Issue by redtopia** [isapir/lucee-websocket#12]
It's not clear how this is done. I don't see a corresponding .jar file to replace in the Lucee folder structure on Windows 7. Thanks.

**Comment by isapir** [comment]
Can't you update it from the Admin like any extension?

You should also be able to download the [.lex file for version 2.0.2](http://extension.lucee.org/rest/extension/provider/full/3F9DFF32-B555-449D-B0EB5DB723044045?version=2.0.2) from http://download.lucee.org/?type=ext and either drop it in the `deploy` directory or upload from the Admin extensions page.

**Comment by redtopia** [comment]
So to install this from the Lucee admin, I need a local file .lex file, correct? I don't see one in the release: https://github.com/isapir/lucee-websocket/releases/tag/2.0.2

**Comment by isapir** [comment]
You need the .lex file, yes.  

OK, I see the source of the confusion.  I updated https://github.com/isapir/lucee-websocket/releases/tag/2.0.2 so that it has the same files as 2.0.1 did.

**Comment by redtopia** [comment]
So just download and install the .lex file? The installer will fetch all the required dependencies?

**Comment by isapir** [comment]
You should still follow the instructions at https://github.com/isapir/lucee-websocket#installation

I'm working with @michaeloffner to make it easier but until that is implemented in Lucee you should follow those instructions.

If you have installed `2.0.1` before then you already have the servlet filter set up, so all you need is to install the Lucee EXtension (or `.lex`) file.

If you have not installed `2.0.1` then follow the instructions at the link above and use `2.0.2` wherever you see `2.0.1`.

**Comment by redtopia** [comment]
Still having issues installing. I tried by first downloading the lucee-websocket-extension-2.0.2.lex file and attempting to install this file. I got an error that said: "C:\lucee\tomcat\temp\servlet-filter-utils-1.1.1.jar (The system cannot find the file specified)". So I downloaded that file and put it in the same folder as the .lex file, but that gave me the same error. So I put the servlet-filter-utils-1.1.1.jar in the tomcat temp folder, but again got the same error.

After it failed the first time, it basically uninstalled the extension. Now when I try to install it, it shows me that I can choose v2.0.2, which I choose. But I get the same error.

**Comment by redtopia** [comment]
I've unsuccessfully tried to install v2.0.2 several times. I finally was able to go back to 1.1.3.1 and then upgraded to 2.0.1. But for some reason, I cannot deploy 2.0.2.

**Comment by isapir** [comment]
Did you follow the instructions at https://github.com/isapir/lucee-websocket#update-july-14th-2017 ?

>So I downloaded that file and put it in the same folder as the .lex file

This is **not** the right place to put it.  From the link above:

>Save the jar file servlet-filter-utils-1.1.1.jar to the classpath, e.g. if you're using Tomcat it can go into {tomcat}/lib, or if you're using Jetty then it can go into {jetty}/lib/ext

**Comment by redtopia** [comment]
Yes, I followed those instructions, and it fails.

**Comment by isapir** [comment]
>So I downloaded that file and put it in the same folder as the .lex file

**This is not the place according to the instructions.**  Please re-read them.

**Comment by redtopia** [comment]
To be clear, I only did that once to see if it would work. I followed the instructions (july 14th update) multiple times and it fails.

**Comment by isapir** [comment]
>I got an error that said: "C:\lucee\tomcat\temp\servlet-filter-utils-1.1.1.jar (The system cannot find the file specified)"

Where do you see this error?  

`C:\lucee\tomcat\temp\servlet-filter-utils-1.1.1.jar` is obviously some path that was added by you somewhere because it's definitely not in the extension nor on my system, so please find out also where is this path coming from.

**Comment by redtopia** [comment]
it shows up when I try to update the extension to v.2.0.2 from the server admin. This is just another method that I tried. I don't see any errors when I try to install it though the deploy directory as per your instructions.

**Comment by redtopia** [comment]
There are no errors and the extension is not installed. I'll be happy to check log files if you tell me which ones to check.

**Comment by isapir** [comment]
There might be a `deploy` log but I'm not sure without checking.  I'll have to test it myself when I have a moment.

**Comment by redtopia** [comment]
Just tried it again, and this is what the deploy log says:

```
"INFO","Thread-1085","09/27/2017","16:40:55","extension","deploy fld lucee-websocket-functions.fld"
"ERROR","Thread-1085","09/27/2017","16:40:56","","Extension;C:\lucee\tomcat\temp\servlet-filter-utils-1.1.1.jar (The system cannot find the file specified);lucee.runtime.exp.NativeException: C:\lucee\tomcat\temp\servlet-filter-utils-1.1.1.jar (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at lucee.runtime.osgi.BundleInfo.<init>(BundleInfo.java:91)
	at lucee.runtime.osgi.BundleFile.<init>(BundleFile.java:42)
	at lucee.runtime.osgi.BundleFile.<init>(BundleFile.java:38)
	at lucee.runtime.config.XMLConfigAdmin.updateJar(XMLConfigAdmin.java:1070)
	at lucee.runtime.config.XMLConfigAdmin.updateRHExtension(XMLConfigAdmin.java:4865)
	at lucee.runtime.config.XMLConfigAdmin.updateRHExtension(XMLConfigAdmin.java:4812)
	at lucee.runtime.config.XMLConfigAdmin._updateRHExtension(XMLConfigAdmin.java:4792)
	at lucee.runtime.config.DeployHandler.deploy(DeployHandler.java:81)
	at lucee.runtime.engine.Controler.control(Controler.java:213)
	at lucee.runtime.engine.Controler.access$000(Controler.java:59)
	at lucee.runtime.engine.Controler$ControlerThread.run(Controler.java:110)
Caused by: java.io.FileNotFoundException: C:\lucee\tomcat\temp\servlet-filter-utils-1.1.1.jar (The system cannot find the file specified)
	... 16 more
"
```

**Comment by isapir** [comment]
I'll look into it.  Thanks.

**Comment by isapir** [comment]
Please try `2.0.3` -- it's the same code as `2.0.2` but packaged a bit differently and should resolve this issue.

**Comment by psarin** [comment]
Where can we find "servlet-filter-utils-1.1.1.jar"?

**Comment by isapir** [comment]
> Where can we find "servlet-filter-utils-1.1.1.jar"?

@psarin  Is that for initializing the Session object?  You can use net.twentyonesolutions.servlet.listener.HttpSessionInitializer which comes with the WebSocket extension.  See 

https://github.com/isapir/lucee-websocket/blob/master/src/main/java/net/twentyonesolutions/servlet/listener/HttpSessionInitializer.java#L11

**Comment by artknight** [comment]
@isapir reading the thread I am a bit confused on the whole installation process. Please correct me if I am wrong

Step 1: Go to the Lucee Admin and install the `Websockets Application 2.0.3`. That should be it?

- Do I still need to copy/paste the `servlet-filter-utils-1.1.1.jar` into the `tomcat/lib` directory?
- Do you I need to add the code below to web.xml?
```
<!-- Required for the Lucee WebSocket Extension !-->    
    <filter>
      <filter-name>HttpSessionInitializerFilter</filter-name>
      <filter-class>net.twentyonesolutions.servlet.filter.HttpSessionInitializerFilter</filter-class>
    </filter>

    <filter-mapping>
      <filter-name>HttpSessionInitializerFilter</filter-name>
      <!-- modify url-pattern to match your websocket endpoints !-->
      <url-pattern>/ws/*</url-pattern>
    </filter-mapping>
```

Thanks!
Art
